export const INSTRUCTIONS_VI = <any>{
    "head": "Đi thẳng",
    "go": "Đi",
    "straight": "thẳng",
    "northwest": "về phía tây bắc",
    "southwest": "về phía tây name",
    "southeast": "về phía đông nam",
    "northeast": "về phía đông bắc",
    "south": "về phía nam",
    "north": "về phía bắc",
    "west": "về phía tây",
    "east": "về phía đông",
    "turn": "Rẽ",
    "merge": "Rẽ",
    "keep": "Rẽ",
    "onto": "vào",
    "exit": "Ra khỏi",
    "the": " ",
    "traffic": " ",
    "make": " ",
    "a": " ",
    "to": " ",
    "on": " ",
    "at": " ",
    "slightly": " ",
    "and": "và",
    "take": "Đi theo lối ra",
    "1st": "thứ nhất",
    "2nd": "thứ hai",
    "3rd": "thứ ba",
    "fork": "ngã ba",
    "enter": "Vào",
    "stay": "để đi vào",
    "sharp": "Rẽ ngoặt",
    "slight": "Rẽ một chút",
    "circle": "vòng xuyến",
    "continue": "Đi tiếp",
    "left": "trái",
    "right": "phải",
    "ramp": "dốc",
    "towards": "về phía",
    "you": " ",
    "your": " ",
    "have": " ",
    "arrived": " ",
    "destination": "Điểm đến của bạn",
    "destination,": "Điểm đến của bạn nằm bên",
    icons: {
        straight: 'straight',
        left: 'turn_left',
        right: 'turn_right',
        merge: 'merge',
        fork_right: 'fork_right',
        fork_left: 'fork_left',
        turn_slight_right: 'turn_slight_right',
        turn_slight_left: 'turn_slight_left',
        turn_sharp_right: 'turn_sharp_right',
        turn_sharp_left: 'turn_sharp_left',
        roundabout_right: 'roundabout_right',
        roundabout_left: 'roundabout_left',
        ramp_right: 'ramp_right',
        ramp_left: 'ramp_left',
        sports_score: 'sports_score',
    }
}